//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBM.Web.ServicioWCF {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioWCF.IServicioUsuario")]
    public interface IServicioUsuario {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUsuario/ObtenerUsuario", ReplyAction="http://tempuri.org/IServicioUsuario/ObtenerUsuarioResponse")]
        BPM_SAS.Entidades.Usuario ObtenerUsuario(int pID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUsuario/ObtenerUsuario", ReplyAction="http://tempuri.org/IServicioUsuario/ObtenerUsuarioResponse")]
        System.Threading.Tasks.Task<BPM_SAS.Entidades.Usuario> ObtenerUsuarioAsync(int pID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUsuario/ObtenerUsuarios", ReplyAction="http://tempuri.org/IServicioUsuario/ObtenerUsuariosResponse")]
        System.Collections.Generic.List<BPM_SAS.Entidades.Usuario> ObtenerUsuarios();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUsuario/ObtenerUsuarios", ReplyAction="http://tempuri.org/IServicioUsuario/ObtenerUsuariosResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BPM_SAS.Entidades.Usuario>> ObtenerUsuariosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUsuario/Insert", ReplyAction="http://tempuri.org/IServicioUsuario/InsertResponse")]
        bool Insert(BPM_SAS.Entidades.Usuario pUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUsuario/Insert", ReplyAction="http://tempuri.org/IServicioUsuario/InsertResponse")]
        System.Threading.Tasks.Task<bool> InsertAsync(BPM_SAS.Entidades.Usuario pUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUsuario/Delete", ReplyAction="http://tempuri.org/IServicioUsuario/DeleteResponse")]
        bool Delete(int pID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUsuario/Delete", ReplyAction="http://tempuri.org/IServicioUsuario/DeleteResponse")]
        System.Threading.Tasks.Task<bool> DeleteAsync(int pID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUsuario/Update", ReplyAction="http://tempuri.org/IServicioUsuario/UpdateResponse")]
        bool Update(BPM_SAS.Entidades.Usuario pUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUsuario/Update", ReplyAction="http://tempuri.org/IServicioUsuario/UpdateResponse")]
        System.Threading.Tasks.Task<bool> UpdateAsync(BPM_SAS.Entidades.Usuario pUser);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioUsuarioChannel : PBM.Web.ServicioWCF.IServicioUsuario, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioUsuarioClient : System.ServiceModel.ClientBase<PBM.Web.ServicioWCF.IServicioUsuario>, PBM.Web.ServicioWCF.IServicioUsuario {
        
        public ServicioUsuarioClient() {
        }
        
        public ServicioUsuarioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioUsuarioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioUsuarioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioUsuarioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BPM_SAS.Entidades.Usuario ObtenerUsuario(int pID) {
            return base.Channel.ObtenerUsuario(pID);
        }
        
        public System.Threading.Tasks.Task<BPM_SAS.Entidades.Usuario> ObtenerUsuarioAsync(int pID) {
            return base.Channel.ObtenerUsuarioAsync(pID);
        }
        
        public System.Collections.Generic.List<BPM_SAS.Entidades.Usuario> ObtenerUsuarios() {
            return base.Channel.ObtenerUsuarios();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BPM_SAS.Entidades.Usuario>> ObtenerUsuariosAsync() {
            return base.Channel.ObtenerUsuariosAsync();
        }
        
        public bool Insert(BPM_SAS.Entidades.Usuario pUser) {
            return base.Channel.Insert(pUser);
        }
        
        public System.Threading.Tasks.Task<bool> InsertAsync(BPM_SAS.Entidades.Usuario pUser) {
            return base.Channel.InsertAsync(pUser);
        }
        
        public bool Delete(int pID) {
            return base.Channel.Delete(pID);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAsync(int pID) {
            return base.Channel.DeleteAsync(pID);
        }
        
        public bool Update(BPM_SAS.Entidades.Usuario pUser) {
            return base.Channel.Update(pUser);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateAsync(BPM_SAS.Entidades.Usuario pUser) {
            return base.Channel.UpdateAsync(pUser);
        }
    }
}
